[package]
name = "vdf-to-json"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
keyvalues-serde = "0.1.0"
serde = "1.0.164"
serde_json = "1.0.99"
