# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: On push to master branch

on:
  push:
    branches: [master]
    paths-ignore:
      - ".github/**"
      - "*.md"

jobs:
  run-tests:
    uses: ./.github/workflows/run-tests.yml
    with:
      target: ${{ github.sha }}

  build:
    uses: ./.github/workflows/build.yml
    with:
      target: ${{ inputs.target }}

  create-release:
    needs: [build]
    uses: ./.github/workflows/create-release.yml
    secrets: inherit
    with:
      channel: main
      target: ${{ github.sha }}
      tag: build-master-${{ github.sha }}

  create-legacy-release:
    needs: [build]
    uses: ./.github/workflows/create-legacy-release.yml
    with:
      target: ${{ github.sha }}
      tag: latest
